config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'help', to: 'static_pages#help'
  get 'contact', to: 'static_pages#contact'

  get 'signup(/:invitation_token)', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :tracks, only: [:index, :show]
  resources :circuits, only: [:index, :show]
  resources :athletes do
    resource :profile
    get 'career_medals', on: :collection
  end
  resources :seasons, only: [:index, :show]

  resources :timesheets do
    get 'copy', on: :member

    resources :entries, shallow: true do
      collection { post :sort }
      resources :runs, shallow: true, except: :index
    end
    resources :points, only: [:index, :create]
  end

  resources :invitations, only: [:create]
  resources :points

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end
  end

  get 'search', to: 'search#index'
  get '/rankings/', to: 'seasons#rankings', as: 'rankings'

  namespace :admin do
    resources :tracks
    resources :users
    resources :circuits
    resources :points
    resources :runs, only: :index
    resources :invitations
    resources :articles, only: [:index, :destroy]
    resources :timesheets
    resources :temporary_timesheets
    get 'import', to: 'timesheet_imports#new', as: 'timesheet_import'
    post 'import', to: 'timesheet_imports#create'
  end

  namespace :api do # , defaults: { format: :json }
    namespace :v1 do
      resources :athletes, only: [:index, :show]
      resources :tracks, only: [:index, :show]
      resources :circuits, only: [:index, :show]
      resources :timesheets, only: [:index, :show] do
        resource :graph, only: [:create] do
          member do
            get 'by_run'
          end
        end
      end
      resources :entries
      # resources :users
      resources :seasons do
        get '/athletes/:athlete_id', to: 'seasons#athletes', on: :member
        get 'men', on: :member
        get 'women', on: :member
      end
      get '/rankings/:season_name', to: 'seasons#rankings'
    end
  end

  get '/become/:id', to: 'admin#become'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  # match '/about', to: 'static_pages#about', via: 'get'
  # match '/signup', to: 'users#new', via: 'get'
  # match '/signin', to: 'sessions#new', via: 'get'
  # match '/signout', to: 'sessions#destroy', via: 'delete'
  # match 'timesheets/:timesheet_id/startlist', to: 'entries#index', via: 'get'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @runs = Run.count
    @timesheets = Timesheet.count
    @athletes = Athlete.count
    @articles = Article.limit(5)
  end

  def about
  end

  def terms
  end

  def privacy
  end

  def contact
  end

  def help
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="container">
  <div class="col-md-8">
    <h1 class="page-header">About Sledsheet</h1>
    <p class="lead">Sledsheet was created in 2010 by skeleton athlete <a href="http://www.sledsheet.com/athletes/1">Kyle Tress</a>.</p>

    <p>I was looking for a way to organize and analyze my timesheets without resorting to spreadsheets, which was the common method at the time. Spreadsheets have many uses, but as soon as you have more than a few, they become impossible to sort and search through. Although I had worked as a web designer for many years, I didn't have the programming skill to build the site myself, so I began to teach myself how to code.</p>

    <p>I rebuilt sledsheet at least 3 times as I learned new things and my skills improved. But I always used the app extensively to graph my runs and track my progress. I built a personal database of hundreds of training runs, and I began to see the value in releasing it to the skeleton community at-large. Throughout the summer of 2015, I worked extensively to add new features to the app to make it more attractive to skeleton athletes and their fans and supporting staff as well.</p>

    <p>I have big plans for sledsheet. As Marc Andreessen said, <em>software is eating the world</em>. Data analysis and visualization is a trend in sport, and I want to grow sledsheet into a leader in the field, starting with our niche sport.</p>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="jumbo">
  <div class="container">
    <div class="row">
      <h1>It's about time.</h1>
      <p class="lead">Sledsheet is a <span>community</span> for <span>skeleton athletes</span> and their <span>fans</span>.</p>
    </div>
    <div class="row">
      <section class="join">
        <div class="athlete-images">
          <img src="https://secure.gravatar.com/avatar/5eba14816d314532e45d34ce2a138543?s=100" alt="" height="100" width="100" />
          <img src="/matt.jpg" alt="" height="100" width="100" />
          <img src="/katie.jpg" alt="" height="100" width="100" />
          <img src="/martins.jpg" alt="" height="100" width="100" />
          <img src="/lizzy.jpg" alt="" height="100" width="100" />
        </div>
        <h3><%= @runs %> runs by <%= @athletes %> athletes <em>(and growing)</em>.</h3>
        <% unless current_user %>
          <%= form_for Invitation.new, url: invitations_path do |f| %>
            <%= f.text_field :recipient_email, placeholder: 'Email address', class: 'flexinput' %>
            <%= f.submit 'Join the waitlist', class: 'btn btn-sledsheet' %>
          <% end %>
        <% end %>
      </section>
    </div>
  </div>
</div><!--end jumbo-->

<div class="container">
  <section class="row features">
    <div class="col-sm-6">
      <h3>For Athletes</h3>
      <p>Sledsheet has powerful tools for athletes. From timesheet analysis to rich data visualization, it's never been easier to see where you are gaining or losing time on the track. But that's not all. Sledsheet helps you connect with fans like never before.</p>
      <ul>
        <li>Timesheet splits, intermediates, and differences</li>
        <li>Rich data visualization</li>
        <li>Full IBSF Race database</li>
        <li>Custom Press Releases*</li>
        <li>Custom Profile and social media integration</li>
        <li>Export timesheets as PDF</li>
      </ul>
      <%= link_to 'All athlete features', '#', class: 'btn btn-default'%>
    </div>
    <div class="col-sm-6">
    </div>
  </section>

  <section class="row features">
    <div class="col-sm-6">
      <h3>For Fans</h3>
      <p>There has never been a better way to connect with the skeleton community. Receive email notifications when your favorite athletes race. You can also subscribe to tracks, circuits, or entire teams.</p>
      <ul>
        <li>Subscribe to your favorite athletes</li>
        <li>Weekly email notifications</li>
        <li>Full IBSF database</li>
        <li>Message, like, and encourage athletes</li>
      </ul>
      <%= link_to 'All fan features', '#', class: 'btn btn-default'%>
    </div>
  </section>

  <section class="row features">
    <div class="col-sm-6">
      <h3>For Organizations</h3>
      <p>Sledsheet is built with teams in mind. Group message your team, send out timesheets, and store them for future reference. Use our point calculators, send out press releases to your mailing list, and much more.</p>
      <ul>
        <li>Press release generators*</li>
        <li>Point calculators</li>
        <li>Group email and messaging*</li>
        <li>Timesheet storage</li>
        <li>Data analysis and visualization</li>
        <li>Custom timesheets for your team*</li>
      </ul>
      <%= link_to '#', class: 'btn btn-default' do %> All organization features <span><%= icon('arrow-right') %></span>
      <% end %>
    </div>
  </section>
</div>
</div><!--end container-->

app/views/static_pages/privacy.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1 class="page-header">Privacy</h1>

      <p class="lead">Your privacy is critically important to us. At Sledsheet we have a few fundamental principles:</p>

      <ol>
        <li>We don&#8217;t ask you for personal information unless we truly need it. (We can&#8217;t stand services that ask you for things like your gender or income level for no apparent reason.)</li>
        <li>We don&#8217;t share your personal information with anyone except to comply with the law, develop our products, or protect our rights.</li>
        <li class="last">We don&#8217;t store personal information on our servers unless required for the on-going operation of one of our services.</li>
      </ol>

      <p> Below is our privacy policy which incorporates these goals:</p>

      <p>Kyle Tress operates Sledsheet.com. It is Sledsheet&#8217;s policy to respect your privacy regarding any information we may collect while operating our websites.</p>

      <h2 class="section">Website Visitors</h2>

      <p> Like most website operators, Sledsheet collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. Sledsheet&#8217;s purpose in collecting non-personally identifying information is to better understand how Sledsheet&#8217;s visitors use its website. From time to time, Sledsheet may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>

      <p> Sledsheet also collects potentially personally-identifying information like Internet Protocol (IP) addresses. Sledsheet does not use such information to identify its visitors, however, and does not disclose such information, other than under the same circumstances that it uses and discloses personally-identifying information, as described below.</p>

      <h2 class="section">Gathering of Personally-Identifying Information</h2>

      <p> Certain visitors to Sledsheets websites choose to interact with Sledsheet in ways that require Sledsheet to gather personally-identifying information. The amount and type of information that Sledsheet gathers depends on the nature of the interaction. For example, we ask visitors who sign up account at <a href="https://Sledsheet.com">Sledsheet.com</a> to provide a name and email address. Sledsheet collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitors interaction with Sledsheet. Sledsheet does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</p>

      <h2 class="section">Aggregated Statistics</h2>

      <p>Sledsheet may collect statistics about the behavior of visitors to its websites. Sledsheet may display this information publicly or provide it to others. However, Sledsheet does not disclose personally-identifying information other than as described below.</p>

      <h2 class="section">Protection of Certain Personally-Identifying Information</h2>

      <p> Sledsheet discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on Sledsheets behalf or to provide services available at Sledsheets websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using Sledsheets websites, you consent to the transfer of such information to them. Sledsheet will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, Sledsheet discloses potentially personally-identifying and personally-identifying information only when required to do so by law, or when Sledsheet believes in good faith that disclosure is reasonably necessary to protect the property or rights of Sledsheet, third parties or the public at large. If you are a registered user of an Sledsheet website and have supplied your email address, Sledsheet may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with whats going on with Sledsheet and our products. We primarily use our various product blogs to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. Sledsheet takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>
    <h2 class="section">Cookies</h2>
    <p> A cookie is a string of information that a website stores on a visitors computer, and that the visitors browser provides to the website each time the visitor returns. Sledsheet uses cookies to help Sledsheet identify and track visitors, their usage of Sledsheet website, and their website access preferences. Sledsheet visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using Sledsheets websites, with the drawback that certain features of Sledsheets websites may not function properly without the aid of cookies.</p>
    <h2 class="section">Privacy Policy Changes</h2>
    <p> Although most changes are likely to be minor, Sledsheet may change its Privacy Policy from time to time, and in Sledsheets sole discretion. Sledsheet encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.
    </p>

    <p class="note">This Privacy Policy was crafted from <a href="http://automattic.com/privacy/">Wordpress.com's version</a>, which is available under a Creative Commons Sharealike license.</p>

app/views/static_pages/terms.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-8">
   <h1 class="page-header">Terms of Service</h1>

   <p>The following terms and conditions govern all use of the Sledsheet website and all content, services and products available at or through the website. The Website is owned and operated by Kyle Tress. The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, <a href="/privacy/">Sledsheet's Privacy Policy</a>) and procedures that may be published from time to time on this Site by Sledsheet (collectively, the Agreement).</p>

   <p>Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by Sledsheet, acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 13 years old.</p>

   <ol class="terms">
    <li><strong>Your Sledsheet Account and Site.</strong> If you create an account on the Website, you are responsible for maintaining the security of your account and its content, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the Website. You must not describe or assign content to your account in a misleading or unlawful manner, including in a manner intended to trade on the name or reputation of others, and Sledsheet may change or remove any description or keyword that it considers inappropriate or unlawful, or otherwise likely to cause Sledsheet liability. You must immediately notify Sledsheet of any unauthorized uses of your account or any other breaches of security. Sledsheet will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.</li>
    <li><strong>Responsibility of Contributors.</strong> If you operate an account, comment on the Website, post material to the Website, post links on the Website, or otherwise make (or allow any third party to make) material available by means of the Website (any such material, Content), You are entirely responsible for the content of, and any harm resulting from, that Content. That is the case regardless of whether the Content in question constitutes text or graphics. By making Content available, you represent and warrant that:

     <ul>
      <li>the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;</li>
      <li>if your employer has rights to intellectual property you create, you have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content;</li>
      <li>you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;</li>
      <li>the Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;</li>
      <li class="important">the Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</li>
      <li>the Content is not obscene, libelous or defamatory, hateful or racially or ethnically objectionable, and does not violate the privacy or publicity rights of any third party;</li>
      <li>your account is not getting advertised via unwanted electronic messages such as spam links on newsgroups, email lists, other blogs and web sites, and similar unsolicited promotional methods;</li>
      <li>your account is not named in a manner that misleads your readers into thinking that you are another person or company. For example, your account&#8217;s URL or name is not the name of a person other than yourself or company other than your own; and</li>
      <li>you have, in the case of Content that includes computer code, accurately categorized and/or described the type, nature, uses and effects of the materials, whether requested to do so by Sledsheet or otherwise.</li>
     </ul>

     <p>Sledsheet reserves the right to remove any content created on Sledsheet, e.g. timesheets, comments, messages, avatars, etc.) for any reason whatsoever. <strong><a href="/rules">Please read our Rulebook</a> for rules and guidelines on what types of content are deemed inappropriate at Sledsheet.</strong></p>

     <p>Sledsheet reserves the right to ban any member or website from using the service for any reason.</p>

     <p>By uploading your data to Sledsheet you give Sledsheet permission to use or distribute your data on sledsheet.com or affiliated sites.</p>

     <p>All images uploaded are copyright &copy; their respective owners.</p>

     <p>If you delete Content, Sledsheet will use reasonable efforts to remove it from the Website, but you acknowledge that caching or references to the Content may not be made immediately unavailable.</p>

     <p>Without limiting any of those representations or warranties, Sledsheet has the right (though not the obligation) to, in Sledsheet&#8217;s sole discretion (i) refuse or remove any content that, in Sledsheet&#8217;s reasonable opinion, violates any Sledsheet policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in Sledsheet&#8217;s sole discretion. Sledsheet will have no obligation to provide a refund of any amounts previously paid.</li>

     <li><strong>Responsibility of Website Visitors.</strong> Sledsheet has not reviewed, and cannot review, all of the material posted to the Website, and cannot therefore be responsible for that materials content, use or effects. By operating the Website, Sledsheet does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. Sledsheet disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.</li>

     <li><strong>Content Posted on Other Websites.</strong> We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which Sledsheet links, and that link to Sledsheet. Sledsheet does not have any control over those non-Sledsheet websites and webpages, and is not responsible for their contents or their use. By linking to a non-Sledsheet website or webpage, Sledsheet does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. Sledsheet disclaims any responsibility for any harm resulting from your use of non-Sledsheet websites and webpages.</li>

     <li><strong>Intellectual Property.</strong> This Agreement does not transfer from Sledsheet to you any Sledsheet or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with Sledsheet. Sledsheet, the Sledsheet logo, and all other trademarks, service marks, graphics and logos used in connection with Sledsheet, or the Website are trademarks or registered trademarks of Sledsheet or Sledsheets licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any Sledsheet or third-party trademarks.</li>

     <li><strong>Changes.</strong> Sledsheet reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. Sledsheet may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement. <strong><br />
</strong></li>

     <li><strong>Termination. </strong>Sledsheet may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your Sledsheet account (if you have one), you may simply discontinue using the Website. Notwithstanding the foregoing, if you have a VIP Services account, such account can only be terminated by Sledsheet if you materially breach this Agreement and fail to cure such breach within thirty (30) days from Sledsheets notice to you thereof; provided that, Sledsheet can terminate the Website immediately as part of a general shut down of our service. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability. <strong><br />
</strong></li>
<li class="important"><strong>Disclaimer of Warranties.</strong> The Website is provided &#8220;as is&#8221;. Sledsheet and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither Sledsheet nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</li>
<li class="important"><strong>Limitation of Liability.</strong> In no event will Sledsheet, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement or substitute products or services; (iii) for interuption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to Sledsheet under this agreement during the twelve (12) month period prior to the cause of action. Sledsheet shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</li>
<li><strong>General Representation and Warranty.</strong> You represent and warrant that (i) your use of the Website will be in strict accordance with the Sledsheet Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.</li>
<li><strong>Indemnification.</strong> You agree to indemnify and hold harmless Sledsheet, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys fees, arising out of your use of the Website, including but not limited to out of your violation this Agreement.</li>
<li class="last"><strong>Miscellaneous.</strong> This Agreement constitutes the entire agreement between Sledsheet and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of Sledsheet, or by the posting by Sledsheet of a revised version. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the state of New York, U.S.A.</li>
</ol>

<p class="note">This Terms of Service was crafted from <a href="http://wordpress.com/tos/">Wordpress.com's version</a>, which is available under a Creative Commons Sharealike license.</p>


</div>
</div>
</div>