config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'help', to: 'static_pages#help'
  get 'contact', to: 'static_pages#contact'

  get 'signup(/:invitation_token)', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :tracks, only: [:index, :show]
  resources :circuits, only: [:index, :show]
  resources :athletes do
    resource :profile
    get 'career_medals', on: :collection
  end
  resources :seasons, only: [:index, :show]

  resources :timesheets do
    get 'copy', on: :member

    resources :entries, shallow: true do
      collection { post :sort }
      resources :runs, shallow: true, except: :index
    end
    resources :points, only: [:index, :create]
  end

  resources :invitations, only: [:create]
  resources :points

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end
  end

  get 'search', to: 'search#index'
  get '/rankings/', to: 'seasons#rankings', as: 'rankings'

  namespace :admin do
    resources :tracks
    resources :users
    resources :circuits
    resources :points
    resources :runs, only: :index
    resources :invitations
    resources :articles, only: [:index, :destroy]
    resources :timesheets
    resources :temporary_timesheets
    get 'import', to: 'timesheet_imports#new', as: 'timesheet_import'
    post 'import', to: 'timesheet_imports#create'
  end

  namespace :api do # , defaults: { format: :json }
    namespace :v1 do
      resources :athletes, only: [:index, :show]
      resources :tracks, only: [:index, :show]
      resources :circuits, only: [:index, :show]
      resources :timesheets, only: [:index, :show] do
        resource :graph, only: [:create] do
          member do
            get 'by_run'
          end
        end
      end
      resources :entries
      # resources :users
      resources :seasons do
        get '/athletes/:athlete_id', to: 'seasons#athletes', on: :member
        get 'men', on: :member
        get 'women', on: :member
      end
      get '/rankings/:season_name', to: 'seasons#rankings'
    end
  end

  get '/become/:id', to: 'admin#become'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  # match '/about', to: 'static_pages#about', via: 'get'
  # match '/signup', to: 'users#new', via: 'get'
  # match '/signin', to: 'sessions#new', via: 'get'
  # match '/signout', to: 'sessions#destroy', via: 'delete'
  # match 'timesheets/:timesheet_id/startlist', to: 'entries#index', via: 'get'
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  has_one :recipient, class_name: 'User'

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :recipient_email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validate :recipient_is_not_registered

  before_create :generate_token

  enum status: [:pending, :claimed, :waitlist]

  scope :pending, -> {where(status: 0)}
  scope :claimed, -> {where(status: 1)}
  scope :waitlist, -> {where(status: 2)}

  private

    def recipient_is_not_registered
      errors.add :recipient_email, 'Already registered' if User.find_by(email: recipient_email)
    end

    def generate_token
      self.token = SecureRandom.urlsafe_base64
    end

end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < AdminController

  def new
    @invitation = Invitation.new
  end

  def index
    @invitations = Invitation.all
  end

  def create
    @invitation = Invitation.new(invitation_params)
    @invitation.sender = current_user
    @invitation.status = "pending"
    if @invitation.save
      InvitationMailer.invitation(@invitation).deliver_later
      flash[:success] = "Invitation sent."
      redirect_to admin_invitations_path
    else
      flash[:success] = "Thanks, we've added you to the waitlist."
      redirect_to root_path
    end
  end

  # Mail a waitlist invitation
  def update
    @invitation = Invitation.find(params[:id])
    @invitation.sender = current_user
    @invitation.status = "pending"
    if @invitation.save
      InvitationMailer.invitation(@invitation).deliver_later
      flash[:success] = "Invitation sent."
      redirect_to admin_invitations_path
    else
      flash[:success] = "Did not send invite."
    end
  end

  def destroy
    Invitation.find(params[:id]).destroy
    flash[:success] = "Invitation has been revoked."
    redirect_to admin_invitations_path
  end

  private

  def invitation_params
    params.require(:invitation).permit(:recipient_email)
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  def create
    @invitation = Invitation.new(invitation_params)
    @invitation.status = "waitlist"
    if @invitation.save
      flash[:success] = "Thanks, we've added you to the waitlist."
      redirect_to root_path
    else
      flash[:error] = "Sorry, we couldn't add you. Are you already on the wait list?"
      redirect_to root_path
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:recipient_email)
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/admin/invitations/index.html.erb
<p><%= link_to 'Send an invitation', new_admin_invitation_path, class: 'btn btn-success'%></p>

<div class="row">
  <div class="col-sm-12">
    <h3>Invitations</h3>
    <table class="table table-bordered">
      <% @invitations.each do |invitation| %>
      <tr>
        <td><%= mail_to invitation.try(:recipient_email), invitation.try(:recipient_email) %></td>
        <td><span class="text-muted"><%= invitation.status %></span></td>
        <% if invitation.status == "claimed" %>
          <td></td>
        <% elsif invitation.status == "pending" %>
          <td><%= link_to "Delete", admin_invitation_path(invitation), method: :delete, data: { confirm: "You sure?" }, class: 'text-danger' %></td>
        <% else %>
          <td><%= link_to 'Invite', admin_invitation_path(invitation), method: :patch %> or <%= link_to "Delete", admin_invitation_path(invitation), method: :delete, data: { confirm: "You sure?" }, class: 'text-danger' %></td>
        <% end %>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/invitations/new.html.erb
<% provide(:title, "New Invitation") %>
<%= form_for @invitation, url: admin_invitations_path do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :recipient_email, 'Email address' %>
    <%= f.text_field :recipient_email %>
  </div>
  <%= f.submit %>
<% end %>