config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'help', to: 'static_pages#help'
  get 'contact', to: 'static_pages#contact'

  get 'signup(/:invitation_token)', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :tracks, only: [:index, :show]
  resources :circuits, only: [:index, :show]
  resources :athletes do
    resource :profile
    get 'career_medals', on: :collection
  end
  resources :seasons, only: [:index, :show]

  resources :timesheets do
    get 'copy', on: :member

    resources :entries, shallow: true do
      collection { post :sort }
      resources :runs, shallow: true, except: :index
    end
    resources :points, only: [:index, :create]
  end

  resources :invitations, only: [:create]
  resources :points

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end
  end

  get 'search', to: 'search#index'
  get '/rankings/', to: 'seasons#rankings', as: 'rankings'

  namespace :admin do
    resources :tracks
    resources :users
    resources :circuits
    resources :points
    resources :runs, only: :index
    resources :invitations
    resources :articles, only: [:index, :destroy]
    resources :timesheets
    resources :temporary_timesheets
    get 'import', to: 'timesheet_imports#new', as: 'timesheet_import'
    post 'import', to: 'timesheet_imports#create'
  end

  namespace :api do # , defaults: { format: :json }
    namespace :v1 do
      resources :athletes, only: [:index, :show]
      resources :tracks, only: [:index, :show]
      resources :circuits, only: [:index, :show]
      resources :timesheets, only: [:index, :show] do
        resource :graph, only: [:create] do
          member do
            get 'by_run'
          end
        end
      end
      resources :entries
      # resources :users
      resources :seasons do
        get '/athletes/:athlete_id', to: 'seasons#athletes', on: :member
        get 'men', on: :member
        get 'women', on: :member
      end
      get '/rankings/:season_name', to: 'seasons#rankings'
    end
  end

  get '/become/:id', to: 'admin#become'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  # match '/about', to: 'static_pages#about', via: 'get'
  # match '/signup', to: 'users#new', via: 'get'
  # match '/signin', to: 'sessions#new', via: 'get'
  # match '/signout', to: 'sessions#destroy', via: 'delete'
  # match 'timesheets/:timesheet_id/startlist', to: 'entries#index', via: 'get'
end

app/models/temporary_timesheet.rb
class TemporaryTimesheet < ApplicationRecord
  has_one_attached :pdf

  after_create :convert_pdf_to_timesheet

  def clean_response_data
    raw_data.gsub!('"','') # remove quotes around names 
    raw_data.gsub!(/\(\d*\)/,'') # remove split ranks
  end

  private

    def convert_pdf_to_timesheet
      ConvertPdfToTimesheetJob.perform_later(self)
    end

end

app/controllers/admin/temporary_timesheets_controller.rb
class Admin::TemporaryTimesheetsController < ApplicationController

  def new
    @temp = TemporaryTimesheet.new
  end

  def create
    @temp = TemporaryTimesheet.new(temporary_timesheet_params)
    if @temp.save
      flash[:success] = "Timesheet sent for processing."
      redirect_to admin_temporary_timesheet_path(@temp)
    else
      render 'new'
    end
    # ImportTimesheetJob.perform_later(params[:url], params[:finish_td])
    # redirect_to timesheets_path, success: "Your import has started. We'll notify you when it's complete"
  end

  def index
  end

  def show
    @temp = TemporaryTimesheet.find(params[:id])
  end

  private

    def temporary_timesheet_params
      params.require(:temporary_timesheet).permit(:pdf)
    end

end

app/helpers/temporary_timesheets_helper.rb
module TemporaryTimesheetsHelper
end

app/views/admin/temporary_timesheets/index.html.erb
<div class="container">
  <h1>Temporary Timesheets</h1>
  <%= link_to 'Convert a timesheet', new_admin_temporary_timesheet_path, class: 'btn' %>
</div>

app/views/admin/temporary_timesheets/new.html.erb
<div class="container">
  <h2>Convert a timesheet</h2>
  <%= form_for [:admin, @temp] do |f| %>
    <div class="row">
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :pdf, "Upload a PDF to convert" %>
          <%= f.file_field :pdf %>
        </div>
      </div>
    </div>
    <%= submit_tag 'Convert' %>
  <% end %>
</div>

app/views/admin/temporary_timesheets/show.html.erb
<% content_for(:head) do %>
  <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/handsontable@7.0.3/dist/handsontable.full.min.js" %>
  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/handsontable@7.0.3/dist/handsontable.full.min.css" %>
<% end %>

<div class="container" data-raw-csv="<%= CSV.parse(@temp.raw_data).to_json %>">

  <h2>Show Temp</h2>

  <section id="spreadsheet">

  </section>
</div>